version: '3.5'
services:
  postgres:
    image: postgres:14.2-alpine3.15
    container_name: postgres
    environment:
      - POSTGRES_DB=trollsdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "40000:5432"
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:6.7
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "40001:5050"
    networks:
      - postgres
    depends_on:
      - postgres

  springboot:
    build:
      context: .
    container_name: springboot
    networks:
      - postgres
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/trollsdb
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING.JPA.SHOW-SQL=false
      - SPRING.JPA.GENERATE-DDL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SETTINGS.IMPORTREPORT.WEBHOOKURL=${WEBHOOK_URL}

volumes:
  postgres-data:
  pgadmin:

networks:
  postgres:
    driver: bridge
