package ch.ost.newspapercommenttodatabasefetcher.repository;

import ch.ost.newspapercommenttodatabasefetcher.entity.Article;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.PagingAndSortingRepository;

import java.util.Optional;

/**
 * A CRUD-Database repository for Articles. An Implementation of this Interface is automatically generated by Spring.
 */
public interface ArticleRepository extends CrudRepository<Article, String>, PagingAndSortingRepository<Article, String>, JpaSpecificationExecutor<Article> {
    @Override
    Optional<Article> findById(String s); //we might have to add the newspaper as a second identifier if multiple newspapers should be supported
}
