package ch.ost.newspapercommenttodatabasefetcher.repository;

import ch.ost.newspapercommenttodatabasefetcher.entity.Newspaper;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.PagingAndSortingRepository;

/**
 * A CRUD-Database repository for Newspapers. An Implementation of this Interface is automatically generated by Spring.
 */
public interface NewspaperRepository extends CrudRepository<Newspaper, String>, PagingAndSortingRepository<Newspaper, String>, JpaSpecificationExecutor<Newspaper> {
}
